name: autodeploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Making Env File
      uses: SpicyPizza/create-envfile@v1.3

  deploy-master:
    name: Deploy to main
    runs-on: ubuntu-latest
    needs: build
    environment: PROD
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Server Actions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          set -e
          export PATH="/root/.nvm/versions/node/v22.11.0/bin:$PATH"
          echo "PATH: $PATH"
          which npm || { echo "npm not found"; exit 1; }
          npm --version || { echo "npm is not functional"; exit 1; }
          cd /var/www/html/fe || exit
          if [ -d "assets" ]; then
            sudo rm -R assets
          fi
          if [ -f "index.html" ]; then
            sudo rm index.html
          fi
          
          cd /var/www/html/fe/Icaaprio_V1 || exit  
          sudo git pull || exit
                    
          cat <<EOF > .env
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
          VITE_OPENAI_API_KEY=${{ secrets.VITE_OPENAI_API_KEY }}
          VITE_ENABLE_ANALYTICS=${{ secrets.VITE_ENABLE_ANALYTICS }}
          VITE_ENABLE_ADMIN=${{ secrets.VITE_ENABLE_ANALYTICS }}
          VITE_CACHE_DURATION=${{ secrets.VITE_CACHE_DURATION }}
          EOF
          if [ -d "dist" ]; then
            sudo rm -rf dist || true
          fi
          npm install
          npm run build
          cd dist  
          sudo mv * ../../