name: autodeploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Making Env File
      uses: SpicyPizza/create-envfile@v1.3

  deploy-master:
    name: Deploy to main
    runs-on: ubuntu-latest
    needs: build
    environment: PROD
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Server Actions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/html/Icaaprio_V1    
          sudo git pull     
                    
          cat <<EOF > .env
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
          VITE_OPENAI_API_KEY=${{ secrets.VITE_OPENAI_API_KEY }}
          VITE_ENABLE_ANALYTICS=${{ secrets.VITE_ENABLE_ANALYTICS }}
          VITE_ENABLE_ADMIN=${{ secrets.VITE_ENABLE_ANALYTICS }}
          VITE_CACHE_DURATION=${{ secrets.VITE_CACHE_DURATION }}
          EOF

          npm install --force
          npm run build --force
          cd dist  
          sudo mv * ../../